spring.datasource.url=jdbc:postgresql://localhost:5555/appdb
spring.datasource.username=devops
spring.datasource.password=devops
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true